modLoader="javafml"
loaderVersion="[36,)"
license="All Rights Reserved"

[[mods]]
modId="dimensionalinventory"
version="1.0.1"
displayName="DimensionalInventory"
authors="Zanckor"
description='''
This mods allows you to change inventories when player switches dimension. It supports non-vanilla dimensions.
'''
